### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by yanfali**
- node 11 like configurator
 - electron 7
   - dependencies for electron that needed updating
   - serial lib

### CODE REVIEW

**Comment by yanfali** [comment]
@e11i0t23 @zekth I've only tested this on Mac Mojave. Will need you help to test this on windows and or/linux

**Comment by e11i0t23** [comment]
The custom flash feature doesn't seem to work on this o widows i aware i forgot `const prompt = require('electron-prompt');` as an import for that file but even when added feature doesn't do anything when pressed. it outputs starting flashing procedures but should either error out for no board attached or flash neither of which occur

**Comment by yanfali** [comment]
let me load the original and see what it's supposed to do

**Comment by yanfali** [comment]
@e11i0t23 this doesn't actually work on mac at all, so I don't know what's going on. It just stops at DFU-Programmer

**Comment by yanfali** [comment]
> @e11i0t23 this doesn't actually work on mac at all, so I don't know what's going on. It just stops at DFU-Programmer. This was using the original branch

None of the executable bits are set for mac

**Comment by e11i0t23** [comment]
Seems to be working on windows now as well after you fixed the dialog

**Pull request merged**
